vich_uploader:
    db_driver: orm

    mappings:
        parc_image:
            uri_prefix: /images/parcs
            upload_destination: '%kernel.project_dir%/public/images/parcs'
            namer: Vich\UploaderBundle\Naming\UniqidNamer